---
title: "Image Compression using Singular Value Decomposition"
---

```{r,echo=FALSE,warning=FALSE, message=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, warning = FALSE, message = FALSE, echo=FALSE)
```


The first one is the original image followed by the compressed image generated by Singular value decomposition of the image. 

```{r}

df <- as.matrix(read.csv("imageSVD.csv", header=T))
# Matrix A is the dataframe of the pixel values of image A 


A <- t(df)%*%df
# Covariance matrix of matrix A 
# SVD of A 
svd.a <- svd(df) 

eig.sum <- svd.a$d/sum(svd.a$d)
which.eig <- which(cumsum(eig.sum) >= 0.9)
kmin <- which.eig[1]

# number of eigenvectors required to preserve the required amount of variance 


``` 


```{r}
ak  <- svd.a$u[,1:kmin]%*%diag(svd.a$d[1:kmin])%*%t(svd.a$v[,1:kmin]) 

image(t(apply(df,2,rev)), axes = FALSE, col = grey(seq(0, 1, length = 256)))
image(t(apply(ak,2,rev)), axes = FALSE, col = grey(seq(0, 1, length = 256)))


```


